@startuml
  class Order {
    String Id
    String Name

    String OriginPoint
    String OrderDatetime
    String ShippmentPoint
    String ShippmentDatetime
      
    Real TotalCost

    String ApproveByCustomerDatetime
    String ApproveBySupplierDatetime
  }
  note right of Order
    **Id** - внутренний идентификатор заказа
    **Name** - предмет заказа
  end note

  interface OrderService {
    String CreateOrderDraft(String name, CargoType cargoType)
    void AddOrderPositions(String position, Real price, Real amount)
    void ApproveOrder(String orderId)
    void AcceptOrder(String orderId, String acceptPoint)
  }

@enduml
